# Generated by Django 5.1 on 2024-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_score_profile_leagues_profile_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.JSONField(default={'score': []}),
        ),
    ]
