# Generated by Django 5.1 on 2024-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='squad_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
