# Generated by Django 5.1 on 2024-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_squad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_balance',
            field=models.IntegerField(default=12),
        ),
    ]
