# Generated by Django 5.1 on 2024-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availiable_tarnsefere',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='profile',
            name='freehit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tripplecaptin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wildcard',
            field=models.BooleanField(default=True),
        ),
    ]
