# Generated by Django 5.1 on 2024-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='substitution',
            field=models.JSONField(default={'subs': []}),
        ),
    ]
