# Generated by Django 5.1 on 2024-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='benchboast',
            field=models.BooleanField(default=True),
        ),
    ]
