# Generated by Django 5.1 on 2024-09-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_benchboast'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='captin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
