# Generated by Django 5.1 on 2024-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_captin_profile_vice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='round_stataics',
            field=models.JSONField(default={'statics': []}),
        ),
    ]
