# Generated by Django 5.1 on 2024-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='properties_ex',
            field=models.JSONField(default={'benchboas': 35, 'freehit': 35, 'tripplecaptin': 35, 'wildcard': 35}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.JSONField(default={'score': [0]}),
        ),
    ]
