# Generated by Django 5.0.7 on 2024-09-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='squad',
        ),
    ]
