# Generated by Django 5.0.7 on 2024-09-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_team_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='squad',
            field=models.JSONField(default={'squad': []}),
        ),
    ]
