# Generated by Django 5.1 on 2024-09-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_team_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
