# Generated by Django 5.1 on 2024-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_player_current_value_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.TextField(default='https://raw.githubusercontent.com/karim2003-mo/football-images/master/players/'),
        ),
    ]
