# Generated by Django 5.1 on 2024-09-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_player_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team']},
        ),
    ]
