# Generated by Django 5.1 on 2024-09-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'name']},
        ),
    ]
