# Generated by Django 5.1 on 2024-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_leagueinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueinfo',
            name='is_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
